version: '3.8'

services:
  ai-prompt-studio:
    build: .
    ports:
      - "8000:8000"
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - ENVIRONMENT=production
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
    command: uvicorn backend.app:app --host 0.0.0.0 --port 8000
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - ai-prompt-studio
    restart: unless-stopped